feat: auto add .setup.js
eggjs/egg-boilerplate-simple pull request #20
Opened 2017-01-24 08:46 UTC by fengmk2

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-01-24 08:46 UTC, fengmk2 commented
依赖 https://github.com/eggjs/egg-bin/pull/30

2017-01-24 08:56 UTC, fengmk2 commented on boilerplate/test/app/controller/home.test.js
>      return request(app.callback())
这测试代码就只写测试相关的即可。

2017-01-24 08:57 UTC, atian25 requested changes

2017-01-24 08:57 UTC, atian25 commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app();
应用测试里面全局只一个 app ?

如果需要测试不同的 env 的时候呢?

2017-01-24 08:57 UTC, atian25 commented on boilerplate/test/app/controller/home.test.js
> +    assert(app);
看起来单元测试是少写很多东西, 但似乎也没省多少事, 看起来觉得有点心虚 @_@

2017-01-24 08:57 UTC, atian25 commented on package.json
> +    "lint": "eslint *.js boilerplate/app boilerplate/config boilerplate/test boilerplate/*.js",
为何改了这里?

2017-01-24 08:58 UTC, fengmk2 commented on package.json
> +    "lint": "eslint *.js boilerplate/app boilerplate/config boilerplate/test boilerplate/*.js",
我进去调试，会生成 node_modules 等目录

2017-01-24 08:59 UTC, fengmk2 commented on package.json
> +    "lint": "eslint *.js boilerplate/app boilerplate/config boilerplate/test boilerplate/*.js",
去掉了

2017-01-24 08:59 UTC, atian25 commented on package.json
> +    "lint": "eslint *.js boilerplate/app boilerplate/config boilerplate/test boilerplate/*.js",
那应该可以在 .eslintignore 里面过滤掉 node_modules

2017-01-24 09:01 UTC, fengmk2 commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app({ cache: false });
@atian25 90%的情况都不需要 env 的，需要的话，在应用 test 里面自己通过 before 来创建对应 env 的 app

2017-01-24 09:02 UTC, fengmk2 commented on boilerplate/test/app/controller/home.test.js
> +    assert(app);
按 @huacnlee 的经验，少一个字符也是值得的。而且100%地重复写 before after 没道理啊

2017-01-24 09:03 UTC, atian25 commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app({ cache: false });
文档那边应该不需要变吧, 只是这个骨架做了简化.

另外最好在生成的单测文件前面加一个注释:

```js
// app is auto init at `test/.setup.js`
```

2017-01-24 09:06 UTC, fengmk2 commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app({ cache: false });
测试文件里面不是有一个 it 来做这个测试么

2017-01-24 09:06 UTC, atian25 commented on boilerplate/test/app/controller/home.test.js
> +    assert(app);
嗯, 倒是省事, 需要时间习惯下.

一下子的感觉就像 js -> coffee

2017-01-24 09:07 UTC, fengmk2 commented on boilerplate/test/app/controller/home.test.js
> +    // app is auto init at `test/.setup.js`
@atian25 加了

2017-01-24 09:08 UTC, atian25 commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app({ cache: false });
我们在文档里面一般都是介绍全的, 然后引导他们看示例和骨架的时候, before 这些突然没了, 会让人感到迷惑的, 加一句注释说明下好一点.

2017-01-24 09:09 UTC, atian25 commented on boilerplate/test/app/controller/home.test.js
> +    // app is auto init at `test/.setup.js`
+1

2017-01-24 09:09 UTC, atian25 approved these changes

2017-01-24 09:34 UTC, popomore commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app({ cache: false });
默认有 cache 的吧

2017-01-24 09:34 UTC, popomore commented on boilerplate/test/.setup.js
> +afterEach(mm.restore);
这个是不是不要加了，有些单测可能是一个 suite 后 restore

2017-01-24 09:36 UTC, atian25 commented on boilerplate/test/.setup.js
> +  app = global.app = mm.app({ cache: false });
应用测试默认应该打开 cache, 不用 `cache: false` 吧?

2017-01-24 09:36 UTC, atian25 commented on boilerplate/test/.setup.js
> +afterEach(mm.restore);
指的是几个 it 后?

mocha 的 it 有顺序保证的么?

2017-01-24 09:45 UTC, popomore commented on boilerplate/test/.setup.js
> +afterEach(mm.restore);
一个 describe 就是一个 suite，一般按读取顺序吧，不过不会信任这个顺序。

2017-01-24 16:38 UTC, fengmk2 commented
@popomore afterEach 和 cache 都去掉了。

2017-01-24 16:51 UTC, popomore approved these changes

2017-01-24 16:51 UTC, merged

2017-01-24 16:52 UTC, atian25 commented on boilerplate/test/app/controller/home.test.js
> -  afterEach(mm.restore);
这行恢复，afterEach 放到测试示例里？

2017-01-24 17:01 UTC, fengmk2 commented on boilerplate/test/app/controller/home.test.js
> -  afterEach(mm.restore);
先不加吧，目前没有使用到 mock

2017-01-25 03:16 UTC, popomore commented
发个版本？

2017-01-25 06:34 UTC, fengmk2 commented
我发个版本

2017-01-25 06:35 UTC, fengmk2 commented
2.1.0